version: "3.7"
services:

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    command:
      - --http-address
      - 0.0.0.0:4180 
    environment:
      OAUTH2_PROXY_UPSTREAMS: http://host.docker.internal:3000/ 
      OAUTH2_PROXY_PROVIDER_DISPLAY_NAME: Asgardeo
      OAUTH2_PROXY_PROVIDER: oidc 
      OAUTH2_PROXY_OIDC_ISSUER_URL: ${ISSUER}
      OAUTH2_PROXY_CLIENT_ID: ${CLIENT_ID}
      OAUTH2_PROXY_CLIENT_SECRET: ${CLIENT_SECRET}
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: true 
      OAUTH2_PROXY_EMAIL_DOMAINS: '*' 
      OAUTH2_PROXY_REDIRECT_URL: http://localhost:4180/oauth2/callback 
      OAUTH2_PROXY_COOKIE_SECRET: ${OAUTH2_PROXY_COOKIE_SECRET} 
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: true
      OAUTH2_PROXY_SKIP_AUTH_REGEX: '^/$'
      OAUTH2_PROXY_WHITELIST_DOMAINS: 'api.asgardeo.io'
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: true
      # pass OIDC IDToken to upstream via Authorization Bearer header
      OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER: true

    ports:
      - 4180:4180 