openapi: 3.0.0
info:
  title: items-api
  version: 1.0.0
servers:
  - url: http://localhost:9090
paths:
  /items:
    post:
      tags:
        - default
      summary: create
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                id: 1
                name: item one
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - default
      summary: get
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}